#项目端口
server:
  port: 8888

#日志输出
logging:
  #自定义backLog日志格式
  config: classpath:logback-spring.xml
  #在默认基础上，在yml上配置
#  file: F:\\logs\\springboot\\gfzs_smart.log
#  level:
#    root: debug


#spring
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
#
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthlife?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: xxxxx
    #
    #
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #
    maxWait: 60000
    #
    timeBetweenEvictionRunsMillis: 60000
    #
    minEvictableIdleTimeMillis: 300000
    #spring.datasource.validationQuery=SELECT 1 FROM DUAL
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #过滤器
    filters: stat,wall
    #合并mysql
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #
    #useGlobalDataSourceStat=true


  #redis的配置：springboot已经封装好，只需要按照约定在yml写入redis连接配置即可，后面程序可以直接@Autowired 注入RedisTemplate
  redis:
    #Redis
    database: 0
    #服务器ַ
    host: xxx.xxx.xxx.xxx
    #端口
    port: 6379
    #密码
    password: xxxxx
    jedis:
      #线程池
      pool:
        #最大活动数
        max-active: 8
        #最打等待数
        max-wait: -1
        #
        max-idle: 8
        #
        min-idle: 0
    #连接超时时间
    timeout: 30000
    #是否允许ssl连接
    ssl: false
#      cluster:
#        集群时要设置
#        max-redirects: 10
#        #多个时，可用，分隔
#        nodes: "45.18.78.133:6379"


#mybatis配置
mybatis:
  config-xml: mybatis-config.xml
  mapper-xml: /mapper/**.xml
  type-aliases-package: com.bingdeng.mysite.entity
  #debug=true

